### ISSUE TITLE
npx sveltekit-graphql init failure...

### ISSUE THREAD

**Issue by timoconnor** [StafflinePeoplePlus/sveltekit-graphql#26]
FYI, After installing sveltekit-graphql, I get the following error when running

npx sveltekit-graphql init 

```
file:///Users/xxxx/Documents/Code%20Respositories/WebLearn/node_modules/sveltekit-graphql/dist/cli.js:108
            throw new Error('vite.config.ts not found');
                  ^

Error: vite.config.ts not found
    at file:///Users/xxxxx/Documents/Code%20Respositories/WebLearn/node_modules/sveltekit-graphql/dist/cli.js:108:19
    at modifyFile (file:///Users/xxxxx/Documents/Code%20Respositories/WebLearn/node_modules/sveltekit-graphql/dist/cli.js:194:22)
    at async Command.<anonymous> (file:///Users/xxxxx/Documents/Code%20Respositories/WebLearn/node_modules/sveltekit-graphql/dist/cli.js:106:9)
```

This is because I am not using typescript.

**Comment by jamesbirtles** [comment]
Hmm, yes we do make the assumption that you will be using typescript both with the vite config, and in the files we generate. Are you not using typescript at all, or just no for the vite config?

I think we could probably make this work in a JS only environment, it will need some changes to the generation, and I'm not sure how it'll interact with the generated types for both houdini and graphql codegen.
